# Generated by Django 5.1.7 on 2025-03-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, unique=True, verbose_name='Área')),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.CharField(max_length=255, unique=True, verbose_name='Avance')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, unique=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Ley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ley', models.CharField(max_length=255, verbose_name='Texto Ley')),
                ('enlace', models.URLField()),
                ('autores', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('avanceley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leyes.avance')),
                ('boletin', models.ManyToManyField(related_name='boletin', to='leyes.anexo')),
                ('minuta', models.ManyToManyField(related_name='minuta', to='leyes.anexo')),
            ],
        ),
    ]
