# Generated by Django 5.1.7 on 2025-03-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0002_estado_ley_impactoavance_ley_impactociudadano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ley',
            name='boletin',
            field=models.ManyToManyField(related_name='boletin', to='leyes.anexo'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='minuta',
            field=models.ManyToManyField(related_name='minuta', to='leyes.anexo'),
        ),
    ]
