# Generated by Django 5.1.7 on 2025-04-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0003_alter_ley_boletin_alter_ley_minuta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='ley',
            options={'verbose_name': 'Ley', 'verbose_name_plural': 'Leyes'},
        ),
        migrations.AlterField(
            model_name='ley',
            name='avanceley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leyes.avance', verbose_name='Avance de la Ley'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='boletin',
            field=models.ManyToManyField(help_text='Escoja un anexo', related_name='boletin', to='leyes.anexo', verbose_name='Boletín'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='enlace',
            field=models.URLField(blank=True, help_text='Link directo a la ley (https://...)', null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='impactoavance',
            field=models.TextField(blank=True, null=True, verbose_name='Posibilidad de avance'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='impactociudadano',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto en la ciudadanía'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='impactocivilong',
            field=models.TextField(blank=True, null=True, verbose_name='Impacto en orgs sociedad civil'),
        ),
        migrations.AlterField(
            model_name='ley',
            name='ley',
            field=models.CharField(blank=True, help_text='Texto/Título de la ley', max_length=255, null=True, verbose_name='Texto de Ley'),
        ),
    ]
